version: '3.8'

services:
  # app:
  #   container_name: api_inlar
  #   build: .
  #   ports:
  #     - 3333:3333
  #   depends_on:
  #     - mysql
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   networks:
  #     - inlar

  mysql:
    container_name: mysql-inlar
    image: mysql
    ports:
      - 3306:3306
    environment:
      # MYSQL_PASSWORD: ${DATABASE_USER}
      # MYSQL_USER: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: "inlar"
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD} 
    volumes:
      - ./data/mg:/var/lib/mysql
    networks:
      - inlar

networks:
  inlar:
    driver: bridge