-- CreateTable
CREATE TABLE `beneficiario` (
    `IDBENEFICIARIO` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(191) NOT NULL,
    `DATANASC` DATETIME(3) NULL,
    `TIPOPESSOA` VARCHAR(191) NOT NULL DEFAULT 'F',
    `GENERO` VARCHAR(191) NULL,
    `CPF` VARCHAR(11) NULL,
    `RG` VARCHAR(30) NULL,
    `CNPJ` VARCHAR(14) NULL,
    `CONTATO1` VARCHAR(11) NULL,
    `CONTATO2` VARCHAR(11) NULL,
    `CEP` VARCHAR(8) NULL,
    `LOGRADOUDO` VARCHAR(255) NULL,
    `NUMERO` VARCHAR(10) NULL,
    `COMPLEMENTO` VARCHAR(100) NULL,
    `BAIRRO` VARCHAR(100) NULL,
    `CIDADE` VARCHAR(100) NULL,
    `SIGLAESTADO` VARCHAR(2) NULL,
    `OBSERVACOES` TEXT NULL,
    `DATACAD` DATETIME(3) NULL,
    `ATIVO` VARCHAR(1) NOT NULL DEFAULT 'S',

    PRIMARY KEY (`IDBENEFICIARIO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `doador` (
    `IDDOADOR` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(191) NOT NULL,
    `TIPOPESSOA` VARCHAR(191) NOT NULL DEFAULT 'F',
    `CPF` VARCHAR(11) NULL,
    `CNPJ` VARCHAR(14) NULL,
    `CONTATO1` VARCHAR(11) NULL,
    `CONTATO2` VARCHAR(11) NULL,
    `CEP` VARCHAR(8) NULL,
    `LOGRADOUDO` VARCHAR(255) NULL,
    `NUMERO` VARCHAR(10) NULL,
    `COMPLEMENTO` VARCHAR(100) NULL,
    `BAIRRO` VARCHAR(100) NULL,
    `CIDADE` VARCHAR(100) NULL,
    `SIGLAESTADO` VARCHAR(2) NULL,
    `OBSERVACOES` TEXT NULL,
    `DATACAD` DATETIME(3) NULL,
    `ATIVO` VARCHAR(1) NOT NULL DEFAULT 'S',

    PRIMARY KEY (`IDDOADOR`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `empresa` (
    `IDEMPRESA` INTEGER NOT NULL AUTO_INCREMENT,
    `NOMEFANTASIA` VARCHAR(191) NOT NULL,
    `RAZAOSOCIAL` VARCHAR(191) NULL,
    `CNPJ` VARCHAR(14) NULL,
    `CONTATO1` VARCHAR(11) NULL,
    `CONTATO2` VARCHAR(11) NULL,
    `CEP` VARCHAR(8) NULL,
    `LOUGRADOURO` VARCHAR(255) NULL,
    `NUMERO` VARCHAR(10) NULL,
    `COMPLEMENTO` VARCHAR(100) NULL,
    `BAIRRO` VARCHAR(100) NULL,
    `CIDADE` VARCHAR(100) NULL,
    `SIGLAESTADO` VARCHAR(2) NULL,

    PRIMARY KEY (`IDEMPRESA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tipodoacao` (
    `IDTIPODOACAO` INTEGER NOT NULL AUTO_INCREMENT,
    `DESCRICAO` VARCHAR(191) NOT NULL,
    `DATACAD` DATETIME(3) NULL,
    `ATIVO` VARCHAR(1) NOT NULL DEFAULT 'S',

    PRIMARY KEY (`IDTIPODOACAO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `usuario` (
    `IDUSUARIO` INTEGER NOT NULL AUTO_INCREMENT,
    `USUARIO` VARCHAR(50) NOT NULL,
    `SENHA` VARCHAR(16) NOT NULL,
    `EMAIL` VARCHAR(255) NULL,
    `ADMINISTRADOR` VARCHAR(1) NULL DEFAULT 'N',
    `DATACAD` DATETIME(3) NULL,
    `ATIVO` VARCHAR(1) NOT NULL DEFAULT 'S',

    PRIMARY KEY (`IDUSUARIO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
